// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)

import AddressController from "./address_controller"
application.register("address", AddressController)

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)
